site_name: Luong Dinh's Notes
site_url: https://dhluong90.github.io
theme:
  name: material
  palette:
    scheme: default
    primary: white
    accent: black
  features:
    - navigation.instant
    - navigation.tracking
    - search.highlight
    - search.share
  font:
    text: IBM Plex Mono
    code: IBM Plex Mono

extra_css:
  - stylesheets/extra.css
