site_name: Luong Dinh's Notes
site_url: https://dhluong90.github.io
theme:
  name: material
  palette:
    scheme: default
    primary: white
    accent: black
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.tracking
    - search.highlight
    - search.share
  font:
    text: IBM Plex Mono
    code: IBM Plex Mono

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - tables
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
