site_name: Luong Dinh's Notes
site_url: https://dhluong90.github.io
theme:
  name: material # Applies the MkDocs Material theme [1].
  features:
    - toc.integrate # Integrates the table of contents with the section navigation [3].
    - search.highlight # Highlights search results on the page [3].
    - search.suggest # Provides search suggestions [3].
    - search.sharing # Allows sharing search results [3].
    - content.code.copy # Adds a copy button to code blocks [4].
    - content.code.annotate # Likely implied for advanced code highlighting, though not explicitly stated for this feature in the provided text. (Note: The source implies more general code highlighting features, not specifically annotations here)
  palette: # Configures the color palette and dark/light mode toggle [4].
    - scheme: default
      primary: teal
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: lime
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
plugins:
  - blog:
      blog_dir: blog
      post_url_format: "{slug}"
      post_excerpt: optional
      post_excerpt_separator: <!-- more -->
      authors: true
      pagination: true
      pagination_per_page: 5