site_name: Luong Dinh's Notes
site_url: https://dhluong90.github.io
theme:
  name: lux # Applies the MkDocs Material theme [1].
  features:
    - toc.integrate # Integrates the table of contents with the section navigation [3].
    - search.highlight # Highlights search results on the page [3].
    - search.suggest # Provides search suggestions [3].
    - search.sharing # Allows sharing search results [3].
    - content.code.copy # Adds a copy button to code blocks [4].
    - content.code.annotate # Likely implied for advanced code highlighting, though not explicitly stated for this feature in the provided text. (Note: The source implies more general code highlighting features, not specifically annotations here)